version: "3.8"
services:
  dynamodb:
    container_name: dynamodb
    image: amazon/dynamodb-local
    restart: always
    ports:
      - "8000:8000"
  init_dynamodb:
    container_name: init
    image: amazon/aws-cli
    restart: "no"
    depends_on:
      - dynamodb
    environment:
      AWS_REGION: us-east-1
      AWS_ACCESS_KEY_ID: test
      AWS_SECRET_ACCESS_KEY: test
    command:
      - dynamodb
      - create-table
      - --table-name
      - kf-key-management-secret
      - --attribute-definitions
      - AttributeName=userId,AttributeType=S
      - AttributeName=service,AttributeType=S
      - --key-schema
      - AttributeName=userId,KeyType=HASH
      - AttributeName=service,KeyType=RANGE
      - --billing-mode
      - PAY_PER_REQUEST
      - --endpoint-url
      - http://dynamodb:8000

  keycloakdb:
    image: postgres:14.1-alpine
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=keycloakdb
      - POSTGRES_PASSWORD=keycloakdb
      - POSTGRES_DB=keycloakdb
    volumes:
      - keycloak-postgres:/var/lib/postgresql/data

  keycloak:
    image: jboss/keycloak:16.1.1
    container_name: keycloak
    environment:
      - KEYCLOAK_IMPORT=/opt/jboss/keycloak/kf-realm.json
#      - KEYCLOAK_USER=admin
#      - KEYCLOAK_PASSWORD=admin
      - DB_DATABASE=keycloakdb
      - DB_USER=keycloakdb
      - DB_PASSWORD=keycloakdb
      - DB_ADDR=keycloakdb
      - DB_VENDOR=postgres
    depends_on:
      - keycloakdb
    restart: always
    ports:
      - "18080:8080"
    volumes:
      - ./docker/kf-realm.json:/opt/jboss/keycloak/kf-realm.json
      - ./docker/kf-users.json:/opt/jboss/keycloak/standalone/configuration/keycloak-add-user.json

volumes:
  keycloak-postgres:

