# In order to override the following configurations :
# java -jar keys.jar --spring.config.location=classpath:/application.yml,file:./application-prod.yml
spring:
  application:
    name: "keys"
  main:
    allow-bean-definition-overriding: true
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "__TBD__"
  cloud:
    gateway:
      forwarded.enabled: false
      x-forwarded.enabled: false
      x-forwarded.forEnabled: false
      x-forwarded.protoEnabled: false
server:
  port: 8080
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: "application/json"
application:
  debug: false
  # Pipe delimited list of allowed domains.
  cors_allowed_domains: "*"
  # dynamodb:
  #   endpoint: "http://localhost:8000"
  cavatica_root: "https://cavatica-api.sbgenomics.com/v2"
  secret_table: "kf-key-management-secret"
  fence:
    dcf:
      name: "dcf"
      client_id: "Jue4ZBwbuqK87nYbEWldwED7CxER7CgDt2I8a87Q"
      client_secret: "__TBD__"
      proxy_uri: "/dcf"
      token_endpoint: "https://nci-crdc-staging.datacommons.io/user/oauth2/token"
      api_endpoint: "https://nci-crdc-staging.datacommons.io"
      redirect_uri: "https://portal.kidsfirstdrc.org/dcf_redirect/"
      authorize_uri: "https://nci-crdc-staging.datacommons.io/user/oauth2/authorize"
      scope: "openid"
      access_token_lifetime_buffer: 30
      refresh_token_lifetime: 43140 # 30 days - 1 minute
    gen3:
      name: "gen3"
      client_id: "V3TPPDDL2T180uPTGy0bZID114KPsd0jczi0DoxV"
      client_secret: "__TBD__"
      token_endpoint: "https://gen3staging.kidsfirstdrc.org/user/oauth2/token"
      redirect_uri: "https://portal-qa.includedcc.org/gen3_redirect/"
      proxy_uri: "/gen3"
      api_endpoint: "https://gen3staging.kidsfirstdrc.org"
      authorize_uri: "https://gen3staging.kidsfirstdrc.org/user/oauth2/authorize"
      scope: "openid"
      access_token_lifetime_buffer: 30
      refresh_token_lifetime: 43140 # 30 days - 1 minute
    cavatica:
      name: "cavatica"
      client_id: "0438b1968f28481785828c935d9f847a"
      client_secret: "__TBD__"
      token_endpoint: "https://accounts-drsko-dev-vayu.sbgenomics.com/oauth2/token"
      authorize_uri: "https://accounts-drsko-dev-vayu.sbgenomics.com/oauth2/authorization"
      api_endpoint: "https://api-drsko-dev-vayu.sbgenomics.com"
      proxy_uri: "/cavatica2"
      redirect_uri: "https://portal-qa.includedcc.org/cavatica_redirect/"
      access_token_lifetime_buffer: 30
      refresh_token_lifetime: 43140 # 30 days - 1 minute
      scope: "openid"
  kms: "__KMS_KEY_TBD__"

